language: node_js
node_js:
  - 0.8
env:
  - DISPLAY=:99.0
before_install:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli
  - sh ./.travis/install_chrome.sh
  - sh -e /etc/init.d/xvfb start
