language: node_js
node_js:
  - 0.8
before_install:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli
  - sudo chmod 1777 /dev/shm
  - export CHROME=google-chrome-stable_current_amd64.deb
  - wget https://dl.google.com/linux/direct/$CHROME
  - sudo dpkg --install $CHROME || sudo apt-get -f install
  - ls -l /usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
